service:
  name: ${env:NUXT_API_GATEWAY_NAME}

frameworkVersion: '>=1.26.1'

provider:
  name: aws
  runtime: nodejs8.10
  region: ${env:REGION}
  stage: prod

package:
  excludeDevDependencies: true
  exclude:
    - .**
    - .**/*
    - app/**
    - tests/**
    - coverage/**
    - LICENSE
    - README.md
    - package.json
    - yarn-error.log
    - yarn.lock
    - node_modules/**/*.md
    - node_modules/**/bin/**
  include:
    - app/static/part.js
    - server/**
    - nuxt.config.js
    - .nuxt/**

functions:
  handler:
    handler: server/handler.handler
    timeout: 30
    memorySize: 2048
    environment:
      BASE_URL: ${env:BASE_URL}
      REGION: ${env:REGION}
      DOMAIN: ${env:DOMAIN}
    events:
      - http:
          path: '/'
          method: get
      - http:
          path: '{proxy+}'
          method: get
