service:
  name: ${env:NUXT_API_GATEWAY_NAME}

frameworkVersion: '>=1.44.1'

provider:
  name: aws
  runtime: nodejs10.x
  region: ${env:AWS_DEFAULT_REGION}
  stage: prod
  logs:
    restApi: true

package:
  excludeDevDependencies: true
  exclude:
    - .**
    - .**/*
    - app/**
    - tests/**
    - coverage/**
    - LICENSE
    - README.md
    - package.json
    - yarn-error.log
    - yarn.lock
  include:
    - app/static/part.js
    - server/**
    - nuxt.config.js
    - .nuxt/**

plugins:
  - serverless-plugin-aws-alerts
  - serverless-prune-plugin

custom:
  # serverless-plugin-aws-alerts
  alerts:
    stages:
      - alis
      - staging
    topics:
      alarm: "arn:aws:sns:ap-northeast-1:879243243508:AlarmToSlack"
    definitions:
      functionErrors:
        treatMissingData: notBreaching
  # serverless-prune-plugin
  prune:
    automatic: true
    number: 3

functions:
  handler:
    handler: server/handler.handler
    timeout: 30
    memorySize: 2048
    environment:
      BASE_URL: ${env:BASE_URL}
      AWS_DEFAULT_REGION: ${env:AWS_DEFAULT_REGION}
      DOMAIN: ${env:DOMAIN}
    events:
      - http:
          path: '/'
          method: get
      - http:
          path: '{proxy+}'
          method: get
    alarms:
      - functionErrors
