// header
export const SET_STATUS = 'SET_STATUS'

// story
export const SET_STORIES = 'SET_STORIES'
export const SET_STORY = 'SET_STORY'
export const SET_PUBLIC_STORIES = 'SET_PUBLIC_STORIES'
export const UPDATE_TITLE = 'UPDATE_TITLE'
export const UPDATE_BODY = 'UPDATE_BODY'
export const ADD_TAG = 'ADD_TAG'
export const UPDATE_TAG = 'UPDATE_TAG'
export const UPDATE_SUGGESTED_THUMBNAILS = 'UPDATE_SUGGESTED_THUMBNAILS'
export const UPDATE_THUMBNAIL = 'SET_THUMBNAIL'
