export const SET_STORIES = 'SET_STORIES'
export const SET_STORY = 'SET_STORY'
export const UPDATE_TITLE = 'UPDATE_TITLE'
export const UPDATE_BODY = 'UPDATE_BODY'
export const ADD_TAG = 'ADD_TAG'
export const UPDATE_TAG = 'UPDATE_TAG'
