version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: setup yarn
          command: |
            sudo npm install -g yarn@1.6.0

      - run: sudo yarn install --pure-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint
      - run:
          name: Format
          command: |
            yarn format;
            git diff --exit-code --quiet;
            if [ $? = 1 ]; then
              echo 'Unformat file(s) found.';
              exit 1
            fi
      - run: yarn test:coverage
      - store_artifacts:
          path: ~/repo/coverage/lcov-report/

      - run:
          name: deploy
          command: |
            sudo apt-get -y -qq install awscli
            sudo npm install -g serverless
            ./deploy.sh
