version: 2.1

# YAMLのマージ(<<:)を使用したい場合はここに定義する
references:
  ignore_master: &ignore_master
    filters:
      branches:
        ignore:
          - master
  only_master: &only_master
    filters:
      branches:
        only:
          - master
  production_jobs: &production_jobs
    <<: *only_master
    context: common_production_deployment

orbs:
  aws-cli: circleci/aws-cli@0.1.13
  slack: circleci/slack@3.3.0

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.13.0-browsers

commands:
  prepare-aws-cli:
    description: 'AWS CLIを準備'
    steps:
      - aws-cli/install
      - aws-cli/configure

  prepare-resources:
    description: 'リソースを準備'
    steps:
      - checkout

      - run: sudo npm install -g yarn@1.21.1

      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}-{{ checksum "serverless.yml" }}-{{ checksum "yarn.lock" }}
            - v3-dependencies-

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package.json" }}-{{ checksum "serverless.yml" }}-{{ checksum "yarn.lock" }}

  prepare-deployment:
    description: 'デプロイを準備'
    steps:
      - prepare-resources
      - prepare-aws-cli

jobs:
  lint-and-test:
    executor: default
    steps:
      - prepare-resources

      - run: yarn lint

      - run:
          name: 'Format checking'
          command: |
            yarn format;
            git diff --exit-code --quiet;
            if [ $? = 1 ]; then
              echo 'Unformat file(s) found.';
              exit 1
            fi

      - run: yarn test:coverage

      - store_artifacts:
          path: ~/repo/coverage/lcov-report/

  build:
    executor: default
    resource_class: medium+
    steps:
      - prepare-deployment

      - run:
          name: 'Nuxt.jsリソースのビルド。Sentryeへのreleaseとsourcemapの反映も行われる'
          command: |
            # ALIS_APP_IDが無い環境ではビルド&デプロイは行わない。
            # persist_to_workspaceで落ちるため事前にディレクトリを生成している
            mkdir .nuxt
            if [ $ALIS_APP_ID ]; then
              yarn build:ci
            fi

      - persist_to_workspace:
          root: .
          paths:
            - .nuxt/*

  deploy:
    executor: default
    steps:
      - prepare-deployment

      - attach_workspace:
          at: .

      - deploy:
          name: 'Deployment'
          command: |
            if [ $ALIS_APP_ID ]; then
              sudo npm install -g 'serverless@<2.0.0'
              yarn deploy
            fi

  deploy-exclude-master:
    executor: default
    steps:
      - prepare-deployment

      - attach_workspace:
          at: .

      - deploy:
          name: 'Deployment'
          command: |
            if [ $ALIS_APP_ID ] && [ $CIRCLE_PROJECT_USERNAME != 'AlisProject' ]; then
              sudo npm install -g 'serverless@<2.0.0'
              yarn deploy
            fi

  notify-to-slack-for-approval:
    executor: default
    steps:
      - slack/approval:
          message: '本番環境へのデプロイを承認してください'
          color: '#F5E911'

workflows:
  # 本番環境以外のワークフロー
  staging-and-others:
    jobs:
      - lint-and-test
      - build:
          context: common_staging_deployment

      # 本番環境とステージング環境以外へのデプロイ
      # AlisProjectアカウントからフォークした環境での実行を想定
      - deploy-exclude-master:
          <<: *ignore_master
          context: common_staging_deployment
          requires: &test-and-build
            - lint-and-test
            - build

      # ステージング環境へのデプロイ
      - deploy:
          name: deploy-staging
          <<: *only_master
          context: common_staging_deployment
          requires: *test-and-build

  # 本番環境のワークフロー(テスト等無し・承認付き)
  production:
    jobs:
      # stagingで同時にテストを行っているため本番環境ワークフローではテストを行わない
      - notify-to-slack-for-approval:
          <<: *production_jobs
      - approval:
          <<: *production_jobs
          type: approval

      - build:
          name: build-production
          <<: *production_jobs
          requires:
            - approval

      - deploy:
          name: deploy-production
          <<: *production_jobs
          requires:
            - build-production
